version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z.fips
    container_name: minio
    ports:
      - "9000:9000" # Porta para a API
      - "9001:9001" # Porta para a Web UI
    environment:
      - MINIO_ROOT_USER:${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD:${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data # Persistência de dados
    command: server /data --console-address ":9001"
    restart: always

  clickhouse:
    image: clickhouse/clickhouse-server:24.5.5.41-alpine
    container_name: clickhouse
    ports:
      - "8123:8123" # Port for HTTP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse # Data Persistence
    restart: always

volumes:
  minio_data:
    driver: local
  clickhouse_data:
    driver: local
